name: Perl

on:
  push: {}
  workflow_dispatch: {}

permissions:
  contents: read
    
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.36'

    runs-on: ubuntu-latest

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
    - run: perl -v
    - run: echo > date.txt
    - run: echo *.txt
